<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Didar_Reference_Data {
	/**
	 * The original built-in catalog used to seed managed country storage.
	 *
	 * Keep this method separate from countries() so a first-run migration can
	 * recover the canonical keys without recursively reading managed storage.
	 */
	public static function default_countries() {
		return array(
			'iran' => 'ایران',
			'china' => 'چین', 'thailand' => 'تایلند', 'japan' => 'ژاپن', 'south_korea' => 'کره جنوبی',
			'uae' => 'امارات', 'oman' => 'عمان', 'india' => 'هند', 'indonesia' => 'اندونزی',
			'malaysia' => 'مالزی', 'hong_kong' => 'هنگ‌کنگ', 'singapore' => 'سنگاپور', 'qatar' => 'قطر',
			'kuwait' => 'کویت', 'jordan' => 'اردن', 'uzbekistan' => 'ازبکستان', 'sri_lanka' => 'سریلانکا',
			'philippines' => 'فیلیپین', 'vietnam' => 'ویتنام', 'pakistan' => 'پاکستان', 'iraq' => 'عراق',
			'saudi_arabia' => 'عربستان', 'kyrgyzstan' => 'قرقیزستان', 'kazakhstan' => 'قزاقستان', 'mongolia' => 'مغولستان',
			'tajikistan' => 'تاجیکستان', 'greece' => 'یونان', 'france' => 'فرانسه', 'belgium' => 'بلژیک',
			'switzerland' => 'سوئیس', 'germany' => 'آلمان', 'sweden' => 'سوئد', 'austria' => 'اتریش',
			'hungary' => 'مجارستان', 'poland' => 'لهستان', 'finland' => 'فنلاند', 'croatia' => 'کرواسی',
			'spain' => 'اسپانیا', 'denmark' => 'دانمارک', 'norway' => 'نروژ', 'italy' => 'ایتالیا',
			'portugal' => 'پرتغال', 'romania' => 'رومانی', 'netherlands' => 'هلند', 'united_kingdom' => 'انگلیس',
			'slovenia' => 'اسلوونی', 'estonia' => 'استونی', 'czech_republic' => 'چک', 'lithuania' => 'لیتوانی',
			'cyprus' => 'قبرس', 'ireland' => 'ایرلند', 'turkey' => 'ترکیه', 'georgia' => 'گرجستان',
			'canada' => 'کانادا', 'united_states' => 'آمریکا', 'mexico' => 'مکزیک', 'brazil' => 'برزیل',
			'argentina' => 'آرژانتین', 'dominica' => 'دومینیکا', 'south_africa' => 'آفریقای جنوبی', 'tunisia' => 'تونس',
			'egypt' => 'مصر', 'morocco' => 'مراکش', 'ivory_coast' => 'ساحل عاج', 'australia' => 'استرالیا',
		);
	}

	/** Return the active managed country catalog used by all form consumers. */
	public static function countries() {
		return class_exists( 'Didar_Country_Catalog' ) ? Didar_Country_Catalog::get_countries() : self::default_countries();
	}

	public static function countries_for_form( $form_type ) {
		return self::for_form( 'countries', $form_type, self::countries() );
	}

	/** Shared Iranian province/city catalog used by dependent birth-place controls. */
	public static function iran_geography() {
		return array(
			'ardabil' => array( 'label' => 'اردبیل', 'cities' => array(
				'ardabil' => 'اردبیل',
				'khalkhal' => 'خلخال',
				'meshgin_shahr' => 'مشگینشهر',
				'parsabad' => 'پارسآباد',
				'hshtjyn' => 'هشتجین',
				'klvr' => 'کلور',
				'hyr' => 'هیر',
				'arallv' => 'آراللو',
				'smryn' => 'ثمرین',
				'bylh_svar' => 'بیله سوار',
				'jafrabad' => 'جعفرآباد',
				'rzy' => 'رضی',
				'alny' => 'النی',
				'lahrvd' => 'لاهرود',
				'fkhrabad' => 'فخراباد',
				'mradlv' => 'مرادلو',
				'qsabh' => 'قصابه',
				'grmy' => 'گرمی',
				'zhra' => 'زهرا',
				'avltan' => 'اولتان',
				'mghan_sr' => 'مغان سر',
				'aslam_abad' => 'اسلام اباد',
				'gyvy' => 'گیوی',
				'fyrvzabad' => 'فیروزآباد',
				'aby_byglv' => 'آبی بیگلو',
				'nmyn' => 'نمین',
				'anbran' => 'عنبران',
				'nyr' => 'نیر',
				'kvrayym' => 'کوراییم',
				'srayn' => 'سرعین',
				'ardymvsy' => 'اردیموسی',
				'aslandvz' => 'اصلاندوز',
				'bran_alya' => 'بران علیا',
				'tazh_kndangvt' => 'تازه کندانگوت',
				'zyvh' => 'زیوه',
			) ),
			'east_azerbaijan' => array( 'label' => 'آذربایجان شرقی', 'cities' => array(
				'tabriz' => 'تبریز',
				'maragheh' => 'مراغه',
				'marand' => 'مرند',
				'mianeh' => 'میانه',
				'ahr' => 'اهر',
				'srdrvd' => 'سردرود',
				'tbryz1' => 'تبریز1',
				'tbryz2' => 'تبریز2',
				'tbryz3' => 'تبریز3',
				'tbryz4' => 'تبریز4',
				'tbryz5' => 'تبریز5',
				'tbryz6' => 'تبریز6',
				'tbryz7' => 'تبریز7',
				'tbryz_10' => 'تبریز 10',
				'tbryz8' => 'تبریز8',
				'asfhlan' => 'اسفهلان',
				'lahyjan' => 'لاهیجان',
				'khsrvshah' => 'خسروشاه',
				'mhrban' => 'مهربان',
				'shrbyan' => 'شربیان',
				'dvzdvzan' => 'دوزدوزان',
				'basmnj' => 'باسمنج',
				'srab' => 'سراب',
				'khdajvkhrajv' => 'خداجوخراجو',
				'znvz' => 'زنوز',
				'bnab_mrnd' => 'بناب مرند',
				'yamchy' => 'یامچی',
				'dyzj_hsyn_byg' => 'دیزج حسین بیگ',
				'kshksray' => 'کشکسرای',
				'trkmanchay' => 'ترکمانچای',
				'aqknd' => 'آقکند',
				'trk' => 'ترک',
				'achachy' => 'اچاچی',
				'hshtrvd' => 'هشترود',
				'nzrkhryzy' => 'نظرکهریزی',
				'bnab' => 'بناب',
				'khvshh_mhr' => 'خوشه مهر',
				'tykmh_dash' => 'تیکمه داش',
				'klybr' => 'کلیبر',
				'krdkndy' => 'کردکندی',
				'bstan_abad' => 'بستان آباد',
				'svfyan' => 'صوفیان',
				'khamnh' => 'خامنه',
				'shbstr' => 'شبستر',
				'shrfkhanh' => 'شرفخانه',
				'shndabad' => 'شندآباد',
				'sys' => 'سیس',
				'vayqan' => 'وایقان',
				'kvzh_knan' => 'کوزه کنان',
				'daryan' => 'داریان',
				'alyshah' => 'علیشاه',
				'tsvj' => 'تسوج',
				'absh_ahmd' => 'آبش احمد',
				'khvajh' => 'خواجه',
				'arbtan' => 'اربطان',
				'hrys' => 'هریس',
				'zrnq' => 'زرنق',
				'bkhshaysh' => 'بخشایش',
				'klvanq' => 'کلوانق',
				'syh_rvd' => 'سیه رود',
				'jlfa' => 'جلفا',
				'hadyshhr' => 'هادیشهر',
				'mlkan' => 'ملکان',
				'mbark_shhr' => 'مبارک شهر',
				'gvgan' => 'گوگان',
				'tymvrlv' => 'تیمورلو',
				'mmqan' => 'ممقان',
				'aylkhchy' => 'ایلخچی',
				'askv' => 'اسکو',
				'shnd' => 'سهند',
				'azrshhr' => 'آذرشهر',
				'qrh_aghaj' => 'قره آغاج',
				'ajb_shyr' => 'عجب شیر',
				'kharvana' => 'خاروانا',
				'vrzqan' => 'ورزقان',
				'jvan_qlah' => 'جوان قلعه',
				'khmarlv' => 'خمارلو',
				'aashqlv' => 'عاشقلو',
				'laryjan' => 'لاریجان',
				'hvrand' => 'هوراند',
				'lylan' => 'لیلان',
			) ),
			'west_azerbaijan' => array( 'label' => 'آذربایجان غربی', 'cities' => array(
				'urmia' => 'ارومیه',
				'khoy' => 'خوی',
				'mahabad' => 'مهاباد',
				'maku' => 'ماکو',
				'qvshchy' => 'قوشچی',
				'sylvanh' => 'سیلوانه',
				'srv' => 'سرو',
				'nvshyn' => 'نوشین',
				'pyranshhr' => 'پیرانشهر',
				'lajan' => 'لاجان',
				'dyzj_dyz' => 'دیزج دیز',
				'zrabad' => 'زرآباد',
				'ayvavghly' => 'ایواوغلی',
				'qtvr' => 'قطور',
				'fyrvrq' => 'فیرورق',
				'tazh_shhr' => 'تازه شهر',
				'slmas' => 'سلماس',
				'srdsht' => 'سردشت',
				'rbt' => 'ربط',
				'nlas' => 'نلاس',
				'bazrgan' => 'بازرگان',
				'khlyfan' => 'خلیفان',
				'gvg_tph' => 'گوگ تپه',
				'myandvab' => 'میاندوآب',
				'bktash' => 'بکتاش',
				'nqdh' => 'نقده',
				'mhmdyar' => 'محمدیار',
				'symynh' => 'سیمینه',
				'bvkan' => 'بوکان',
				'nazk_alya' => 'نازک علیا',
				'shahyn_dzh' => 'شاهین دژ',
				'mhmvdabad' => 'محمودآباد',
				'kshavrz' => 'کشاورز',
				'tkab' => 'تکاب',
				'tkht_slyman' => 'تخت سلیمان',
				'ashnvyh' => 'اشنویه',
				'nalvs' => 'نالوس',
				'avajyq' => 'آواجیق',
				'syh_chshmh' => 'سیه چشمه',
				'pldsht' => 'پلدشت',
				'hajylar' => 'حاجیلار',
				'qrh_zyaaldyn' => 'قره ضیاءالدین',
				'mrgnlr' => 'مرگنلر',
				'shvt' => 'شوط',
				'yvlagldy' => 'یولاگلدی',
				'chharbrj' => 'چهاربرج',
				'barvq' => 'باروق',
				'myrabad' => 'میرآباد',
			) ),
			'alborz' => array( 'label' => 'البرز', 'cities' => array(
				'karaj' => 'کرج',
				'taleqan' => 'طالقان',
				'nazarabad' => 'نظرآباد',
				'savojbolagh' => 'ساوجبلاغ',
				'mahdsht' => 'ماهدشت',
				'kmal_shhr' => 'کمال شهر',
				'mhmd_shhr' => 'محمد شهر',
				'grmdrh' => 'گرمدره',
				'krj_10' => 'کرج 10',
				'asara' => 'آسارا',
				'hshtgrd' => 'هشتگرد',
				'glsar' => 'گلسار',
				'mhstan' => 'مهستان',
				'kvhsar' => 'کوهسار',
				'tnkman' => 'تنکمان',
				'ashthard' => 'اشتهارد',
				'plng_abad' => 'پلنگ آباد',
				'frdys' => 'فردیس',
				'mshkyn_dsht' => 'مشکین دشت',
				'chharbagh' => 'چهارباغ',
			) ),
			'bushehr' => array( 'label' => 'بوشهر', 'cities' => array(
				'bushehr' => 'بوشهر',
				'borazjan' => 'برازجان',
				'kangan' => 'کنگان',
				'genaveh' => 'گناوه',
				'khark' => 'خارک',
				'bvshhr1' => 'بوشهر1',
				'bvshhr2' => 'بوشهر2',
				'aaly_shhr' => 'عالی شهر',
				'chghadk' => 'چغادک',
				'dlvar' => 'دلوار',
				'dalky' => 'دالکی',
				'ahrm' => 'اهرم',
				'abad' => 'آباد',
				'sad_abad' => 'سعد آباد',
				'vhdtyh' => 'وحدتیه',
				'shbankarh' => 'شبانکاره',
				'tng_arm' => 'تنگ ارم',
				'klmh' => 'کلمه',
				'bvshkan' => 'بوشکان',
				'ab_pkhsh' => 'آب پخش',
				'kaky' => 'کاکی',
				'badvlh' => 'بادوله',
				'khvrmvj' => 'خورموج',
				'shnbh' => 'شنبه',
				'brdkhvn' => 'بردخون',
				'bndrdyr' => 'بندردیر',
				'brdstan' => 'بردستان',
				'dvrahk' => 'دوراهک',
				'abdan' => 'آبدان',
				'bndrkngan' => 'بندرکنگان',
				'bnk' => 'بنک',
				'shyrynv' => 'شیرینو',
				'syraf' => 'سیراف',
				'bndrryg' => 'بندرریگ',
				'bndrgnavh' => 'بندرگناوه',
				'amam_hsn' => 'امام حسن',
				'bndrdylm' => 'بندردیلم',
				'anarstan' => 'انارستان',
				'ryz' => 'ریز',
				'jm' => 'جم',
				'bharstan' => 'بهارستان',
				'aslvyh' => 'عسلویه',
				'nkhl_tqy' => 'نخل تقی',
				'bydkhvn' => 'بیدخون',
				'chah_mbark' => 'چاه مبارک',
			) ),
			'chaharmahal_and_bakhtiari' => array( 'label' => 'چهارمحال و بختیاری', 'cities' => array(
				'shahrekord' => 'شهرکرد',
				'lordegan' => 'لردگان',
				'borujen' => 'بروجن',
				'farrokhshahr' => 'فرخشهر',
				'gndman' => 'گندمان',
				'fradbnh' => 'فرادبنه',
				'sfyddsht' => 'سفیددشت',
				'nqnh' => 'نقنه',
				'bldajy' => 'بلداجی',
				'hfshjan' => 'هفشجان',
				'kyan' => 'کیان',
				'taqank' => 'طاقانک',
				'nafch' => 'نافچ',
				'svrshjan' => 'سورشجان',
				'svdjan' => 'سودجان',
				'harvny' => 'هارونی',
				'farsan' => 'فارسان',
				'gvjan' => 'گوجان',
				'babahydr' => 'بآباحیدر',
				'fyl_abad' => 'فیل آباد',
				'jvnqan' => 'جونقان',
				'prdnjan' => 'پردنجان',
				'chlychh' => 'چلیچه',
				'mnj' => 'منج',
				'srdsht_chaharmahal_and_bakhtiari' => 'سردشت',
				'ardl' => 'اردل',
				'kaj' => 'کاج',
				'dshtk' => 'دشتک',
				'srkhvn' => 'سرخون',
				'bazft' => 'بازفت',
				'chlgrd' => 'چلگرد',
				'smsamy' => 'صمصامی',
				'shlmzar' => 'شلمزار',
				'ghrv' => 'گهرو',
				'dstna' => 'دستنا',
				'naghan' => 'ناغان',
				'saman' => 'سامان',
				'hvrh' => 'هوره',
				'bn' => 'بن',
				'vrdnjan' => 'وردنجان',
				'yan_chshmh' => 'یان چشمه',
				'alvny' => 'آلونی',
				'mal_khlyfh' => 'مال خلیفه',
			) ),
			'fars' => array( 'label' => 'فارس', 'cities' => array(
				'shiraz' => 'شیراز',
				'marvdasht' => 'مرودشت',
				'jahrom' => 'جهرم',
				'lar' => 'لار',
				'abadh' => 'آباده',
				'ayzdkhvast' => 'ایزدخواست',
				'svrmq' => 'سورمق',
				'sghad' => 'صغاد',
				'bhmn' => 'بهمن',
				'shyraz_11' => 'شیراز 11',
				'rvnyz' => 'رونیز',
				'asthban' => 'استهبان',
				'ayj' => 'ایج',
				'dzhkrd' => 'دژکرد',
				'sdh' => 'سده',
				'aqlyd' => 'اقلید',
				'hsn_abad' => 'حسن اباد',
				'dvzh' => 'دوزه',
				'qtb_abad' => 'قطب آباد',
				'rstaq' => 'رستاق',
				'darab' => 'داراب',
				'fdamy' => 'فدامی',
				'dvbrjy' => 'دوبرجی',
				'jnt_shhr' => 'جنت شهر',
				'paskhn' => 'پاسخن',
				'ardkan' => 'اردکان',
				'hmashhr' => 'هماشهر',
				'shyraz1' => 'شیراز1',
				'shyraz2' => 'شیراز2',
				'shyraz3' => 'شیراز3',
				'shyraz4' => 'شیراز4',
				'shyraz5' => 'شیراز5',
				'shyraz6' => 'شیراز6',
				'shhrsdra' => 'شهرصدرا',
				'daryan_fars' => 'داریان',
				'shyraz7' => 'شیراز7',
				'shyraz8' => 'شیراز8',
				'shyraz_10' => 'شیراز 10',
				'khanh_znyan' => 'خانه زنیان',
				'shshdh' => 'ششده',
				'qrh_blagh' => 'قره بلاغ',
				'zahdshhr' => 'زاهدشهر',
				'myanshhr' => 'میانشهر',
				'fsa' => 'فسا',
				'nvbndgan' => 'نوبندگان',
				'fyrvzabad_fars' => 'فیروزآباد',
				'mymnd' => 'میمند',
				'baladh' => 'بالاده',
				'knartkhth' => 'کنارتخته',
				'kazrvn' => 'کازرون',
				'khsht' => 'خشت',
				'ltyfy' => 'لطیفی',
				'khvr' => 'خور',
				'dhkvyh' => 'دهکویه',
				'byrm' => 'بیرم',
				'bnarvyh' => 'بنارویه',
				'amad_shhr' => 'عماد شهر',
				'kamfyrvz' => 'کامفیروز',
				'fth_abad' => 'فتح آباد',
				'zngy_abad' => 'زنگی آباد',
				'ramjrd' => 'رامجرد',
				'mshkan' => 'مشکان',
				'sydan' => 'سیدان',
				'farvq' => 'فاروق',
				'khanymn' => 'خانیمن',
				'babamnyr' => 'بابامنیر',
				'nvrabad' => 'نورآباد',
				'khvmh_zar' => 'خومه زار',
				'ny_ryz' => 'نی ریز',
				'qtrvyh' => 'قطرویه',
				'lamrd' => 'لامرد',
				'ashknan' => 'اشکنان',
				'ahl' => 'اهل',
				'alamrvdsht' => 'علامرودشت',
				'chah_vrz' => 'چاه ورز',
				'khyrgv' => 'خیرگو',
				'bvanat' => 'بوانات',
				'mzayjan' => 'مزایجان',
				'arsnjan' => 'ارسنجان',
				'qadrabad' => 'قادراباد',
				'sfashhr' => 'صفاشهر',
				'shhrpyr' => 'شهرپیر',
				'hajy_abad' => 'حاجی آباد',
				'dbyran' => 'دبیران',
				'afzr' => 'افزر',
				'qyr' => 'قیر',
				'amam_shhr' => 'امام شهر',
				'mbark_abaddyz' => 'مبارک آباددیز',
				'karzyn_fth_abad' => 'کارزین فتح آباد',
				'glh_dar' => 'گله دار',
				'fal' => 'فال',
				'mhr' => 'مهر',
				'vravy' => 'وراوی',
				'khvzy' => 'خوزی',
				'asyr' => 'اسیر',
				'frashbnd' => 'فراشبند',
				'nvjyn' => 'نوجین',
				'dhrm' => 'دهرم',
				'saadt_shhr' => 'سعادت شهر',
				'madrslyman' => 'مادرسلیمان',
				'mhmlh' => 'محمله',
				'tsvj_fars' => 'طسوج',
				'sltan_shhr' => 'سلطان شهر',
				'khnj' => 'خنج',
				'kvhnjan' => 'کوهنجان',
				'srvstan' => 'سروستان',
				'kvpn' => 'کوپن',
				'msyry' => 'مصیری',
				'grash' => 'گراش',
				'ard' => 'ارد',
				'akbrabad' => 'اکبرآباد',
				'mzfry' => 'مظفری',
				'kvar' => 'کوار',
				'khramh' => 'خرامه',
				'mazabadjabry' => 'معزآبادجابری',
				'khyrabad' => 'خیراباد',
				'zrqan' => 'زرقان',
				'lpvyy' => 'لپویی',
				'rhmt_abad' => 'رحمت آباد',
				'byza' => 'بیضا',
				'hsamy' => 'حسامی',
				'krh_ay' => 'کره ای',
				'bagh_sfa' => 'باغ صفا',
				'tvjrdy' => 'توجردی',
				'qaymyh' => 'قایمیه',
				'nvdan' => 'نودان',
				'bab_anar' => 'باب انار',
				'khavran' => 'خاوران',
				'khvajh_jmaly' => 'خواجه جمالی',
				'abadh_tshk' => 'آباده طشک',
				'tm_shvly' => 'تم شولی',
				'avz' => 'اوز',
				'kvrh' => 'کوره',
				'jvym' => 'جویم',
			) ),
			'gilan' => array( 'label' => 'گیلان', 'cities' => array(
				'rasht' => 'رشت',
				'anzali' => 'انزلی',
				'lahijan' => 'لاهیجان',
				'langarud' => 'لنگرود',
				'astara' => 'آستارا',
				'lvndvyl' => 'لوندویل',
				'kyashhr' => 'کیاشهر',
				'astanh_ashrfyh' => 'آستانه اشرفیه',
				'bndranzly' => 'بندرانزلی',
				'hshtpr_talsh' => 'هشتپر تالش',
				'lysar' => 'لیسار',
				'lvshan' => 'لوشان',
				'rvdbar' => 'رودبار',
				'mnjyl' => 'منجیل',
				'rstm_abad' => 'رستم آباد',
				'asalm' => 'اسالم',
				'hvyq' => 'حویق',
				'chvbr' => 'چوبر',
				'sngr' => 'سنگر',
				'kvchsfhan' => 'کوچصفهان',
				'lvlman' => 'لولمان',
				'lsht_nsha' => 'لشت نشاء',
				'pyrbazar' => 'پیربازار',
				'fvmn' => 'فومن',
				'masvlh' => 'ماسوله',
				'maklvan' => 'ماکلوان',
				'chaf_v_chmkhalh' => 'چاف و چمخاله',
				'khshkbyjar' => 'خشکبیجار',
				'tvtkabn' => 'توتکابن',
				'jyrndh' => 'جیرنده',
				'brh_sr' => 'بره سر',
				'rhym_abad' => 'رحیم آباد',
				'rvdsr' => 'رودسر',
				'chabksr' => 'چابکسر',
				'klachay' => 'کلاچای',
				'vajargah' => 'واجارگاه',
				'mrjql' => 'مرجقل',
				'svmah_sra' => 'صومعه سرا',
				'gvrab_zrmykh' => 'گوراب زرمیخ',
				'tahr_gvrab' => 'طاهر گوراب',
				'zyabr' => 'ضیابر',
				'ataqvr' => 'اطاقور',
				'kvmlh' => 'کومله',
				'shlman' => 'شلمان',
				'rvdbnh' => 'رودبنه',
				'ahmd_srgvrab' => 'احمد سرگوراب',
				'shft' => 'شفت',
				'rankvh' => 'رانکوه',
				'amlsh' => 'املش',
				'prh_sr' => 'پره سر',
				'rzvanshhr' => 'رضوانشهر',
				'dylman' => 'دیلمان',
				'syahkl' => 'سیاهکل',
				'bazar_jmah' => 'بازار جمعه',
				'masal' => 'ماسال',
				'khmam' => 'خمام',
				'chvkam' => 'چوکام',
			) ),
			'golestan' => array( 'label' => 'گلستان', 'cities' => array(
				'gorgan' => 'گرگان',
				'gonbad_e_kavus' => 'گنبد کاووس',
				'aliabad_katul' => 'علیآباد کتول',
				'bandar_torkaman' => 'بندر ترکمن',
				'bndrgz' => 'بندرگز',
				'nvkndh' => 'نوکنده',
				'syjval' => 'سیجوال',
				'aly_abad' => 'علی آباد',
				'mzrah' => 'مزرعه',
				'sngdvyn' => 'سنگدوین',
				'fazl_abad' => 'فاضل آباد',
				'krdkvy' => 'کردکوی',
				'jlyn' => 'جلین',
				'srkhnklath' => 'سرخنکلاته',
				'qrq' => 'قرق',
				'krnd' => 'کرند',
				'aynchh_brvn' => 'اینچه برون',
				'fraghy' => 'فراغی',
				'alqjr' => 'القجر',
				'mynvdsht' => 'مینودشت',
				'dvzyn' => 'دوزین',
				'anbar_alvm' => 'انبار آلوم',
				'aq_qla' => 'آق قلا',
				'klalh' => 'کلاله',
				'nvdh_khandvz' => 'نوده خاندوز',
				'azadshhr' => 'آزادشهر',
				'ngyn_shhr' => 'نگین شهر',
				'khan_bbyn' => 'خان ببین',
				'sadq_abad' => 'صادق آباد',
				'ramyan' => 'رامیان',
				'dlnd' => 'دلند',
				'tatar_alya' => 'تاتار علیا',
				'mravh' => 'مراوه',
				'glydagh' => 'گلیداغ',
				'gmysh_tph' => 'گمیش تپه',
				'symyn_shhr' => 'سیمین شهر',
				'ynqaq' => 'ینقاق',
				'galyksh' => 'گالیکش',
			) ),
			'hamadan' => array( 'label' => 'همدان', 'cities' => array(
				'hamadan' => 'همدان',
				'malayer' => 'ملایر',
				'nahavand' => 'نهاوند',
				'asadabad' => 'اسدآباد',
				'frsfj' => 'فرسفج',
				'tvysrkan' => 'تویسرکان',
				'srkan' => 'سرکان',
				'azndryan' => 'ازندریان',
				'jvkar' => 'جوکار',
				'samn' => 'سامن',
				'aslam_shhr_aq_gl' => 'اسلام شهر آق گل',
				'zngnh' => 'زنگنه',
				'fyrvzan' => 'فیروزان',
				'brzvl' => 'برزول',
				'gyan' => 'گیان',
				'qhavnd' => 'قهاوند',
				'mryanj' => 'مریانج',
				'jvrqan' => 'جورقان',
				'gl_tph' => 'گل تپه',
				'kbvdrahng' => 'کبودرآهنگ',
				'shyryn_sv' => 'شیرین سو',
				'palyz' => 'پالیز',
				'dmq' => 'دمق',
				'ajyn' => 'آجین',
				'laljyn' => 'لالجین',
				'mhajran' => 'مهاجران',
				'bhar' => 'بهار',
				'salh_abad' => 'صالح آباد',
				'rzn' => 'رزن',
				'famnyn' => 'فامنین',
				'shahnjryn' => 'شاهنجرین',
				'krfs' => 'کرفس',
				'qrvh_drgzyn' => 'قروه درگزین',
			) ),
			'hormozgan' => array( 'label' => 'هرمزگان', 'cities' => array(
				'bandar_abbas' => 'بندرعباس',
				'kish' => 'کیش',
				'qeshm' => 'قشم',
				'minab' => 'میناب',
				'abvmvsy' => 'ابوموسی',
				'fyn' => 'فین',
				'tazyan_payyn' => 'تازیان پایین',
				'tkht' => 'تخت',
				'qlah_qazy' => 'قلعه قاضی',
				'hrmz' => 'هرمز',
				'chark' => 'چارک',
				'kng' => 'کنگ',
				'bndr_lngh' => 'بندر لنگه',
				'lmzan' => 'لمزان',
				'svza' => 'سوزا',
				'rmkan' => 'رمکان',
				'laft' => 'لافت',
				'drghan' => 'درگهان',
				'tbl' => 'طبل',
				'sndrk' => 'سندرک',
				'tyrvr' => 'تیرور',
				'hshtbndy' => 'هشتبندی',
				'zhvky' => 'زهوکی',
				'krgan' => 'کرگان',
				'bnd_zrk' => 'بند زرک',
				'bndr_jask' => 'بندر جاسک',
				'lyrdf' => 'لیردف',
				'zyartaly' => 'زیارتعلی',
				'dhbarz' => 'دهبارز',
				'bala_shhr' => 'بالا شهر',
				'byka' => 'بیکاء',
				'farghan' => 'فارغان',
				'hajy_abad_hormozgan' => 'حاجی آباد',
				'srgz' => 'سرگز',
				'jnah' => 'جناح',
				'hngvyyh' => 'هنگوییه',
				'bstk' => 'بستک',
				'kvhych' => 'کوهیچ',
				'rvydr' => 'رویدر',
				'khmyr' => 'خمیر',
				'pl' => 'پل',
				'kvshknar' => 'کوشکنار',
				'parsyan' => 'پارسیان',
				'dshty' => 'دشتی',
				'kvhstk' => 'کوهستک',
				'syryk' => 'سیریک',
				'grvk' => 'گروک',
				'srdsht_hormozgan' => 'سردشت',
				'gvhran' => 'گوهران',
			) ),
			'ilam' => array( 'label' => 'ایلام', 'cities' => array(
				'ilam' => 'ایلام',
				'dehloran' => 'دهلران',
				'mehran' => 'مهران',
				'abadanan' => 'آبدانان',
				'jafrabad_ilam' => 'جعفراباد',
				'drh_shhr' => 'دره شهر',
				'mazhyn' => 'ماژین',
				'phlh' => 'پهله',
				'mvsyan' => 'موسیان',
				'mymh' => 'میمه',
				'dsht_abas' => 'دشت عباس',
				'srablh' => 'سرابله',
				'shbab' => 'شباب',
				'blavh' => 'بلاوه',
				'asman_abad' => 'آسمان آباد',
				'salh_abad_ilam' => 'صالح آباد',
				'mvrmvry' => 'مورموری',
				'srab_bagh' => 'سراب باغ',
				'zrnh' => 'زرنه',
				'chvar' => 'چوار',
				'ayvan' => 'ایوان',
				'arkvaz' => 'ارکواز',
				'dlgsha' => 'دلگشا',
				'mhr_ilam' => 'مهر',
				'lvmar' => 'لومار',
				'bdrh' => 'بدره',
				'chshmh_shyryn' => 'چشمه شیرین',
				'tvhyd' => 'توحید',
			) ),
			'isfahan' => array( 'label' => 'اصفهان', 'cities' => array(
				'isfahan' => 'اصفهان',
				'kashan' => 'کاشان',
				'najafabad' => 'نجفآباد',
				'khomeinishahr' => 'خمینیشهر',
				'ardstan' => 'اردستان',
				'zvarh' => 'زواره',
				'mhabad' => 'مهاباد',
				'bydh' => 'بیده',
				'asfhan_15' => 'اصفهان 15',
				'asfhan_10' => 'اصفهان 10',
				'asfhan_12' => 'اصفهان 12',
				'asfhan_13' => 'اصفهان 13',
				'qhjavrstan' => 'قهجاورستان',
				'asfhan_14' => 'اصفهان 14',
				'asfhan_11' => 'اصفهان 11',
				'bharstan_isfahan' => 'بهارستان',
				'zyar' => 'زیار',
				'drchh' => 'درچه',
				'kvshk' => 'کوشک',
				'asghrabad' => 'اصغرآباد',
				'vyst' => 'ویست',
				'khvansar' => 'خوانسار',
				'kmh' => 'کمه',
				'smyrm' => 'سمیرم',
				'hna' => 'حنا',
				'vnk' => 'ونک',
				'fth_abad_isfahan' => 'فتح آباد',
				'daran' => 'داران',
				'damnh' => 'دامنه',
				'frydvnshhr' => 'فریدونشهر',
				'brf_anbar' => 'برف انبار',
				'tad' => 'طاد',
				'pyrbkran' => 'پیربکران',
				'bharan_shhr' => 'بهاران شهر',
				'bvstan_zr' => 'بوستان زر',
				'flavrjan' => 'فلاورجان',
				'klyshad_v_svdrjan' => 'کلیشاد و سودرجان',
				'abryshm' => 'ابریشم',
				'ashtrjan' => 'اشترجان',
				'mynadsht' => 'مینادشت',
				'qhdryjan' => 'قهدریجان',
				'zazran' => 'زازران',
				'shhrza' => 'شهرضا',
				'mnzryh' => 'منظریه',
				'qmsr' => 'قمصر',
				'jvshqan_qaly' => 'جوشقان قالی',
				'kamv_v_chvgan' => 'کامو و چوگان',
				'mshkat' => 'مشکات',
				'nyasr' => 'نیاسر',
				'brzk' => 'برزک',
				'glpaygan' => 'گلپایگان',
				'gvgd' => 'گوگد',
				'glshhr' => 'گلشهر',
				'bagh_bhadran' => 'باغ بهادران',
				'chrmhyn' => 'چرمهین',
				'chmgrdan' => 'چمگردان',
				'zryn_shhr' => 'زرین شهر',
				'sdh_lnjan' => 'سده لنجان',
				'vrnamkhvast' => 'ورنامخواست',
				'fvladshhr' => 'فولادشهر',
				'zayndh_rvd' => 'زاینده رود',
				'baghshad' => 'باغشاد',
				'anark' => 'انارک',
				'nayyn' => 'نایین',
				'bafran' => 'بافران',
				'jvzdan' => 'جوزدان',
				'gldsht' => 'گلدشت',
				'khryzsng' => 'کهریزسنگ',
				'dhq' => 'دهق',
				'alvyjh' => 'علویجه',
				'ntnz' => 'نطنز',
				'trq_rvd' => 'طرق رود',
				'badrvd' => 'بادرود',
				'khaldabad' => 'خالدآباد',
				'mymh_isfahan' => 'میمه',
				'vzvan' => 'وزوان',
				'lay_byd' => 'لای بید',
				'shahyn_shhr' => 'شاهین شهر',
				'gzbrkhvar' => 'گزبرخوار',
				'grgab' => 'گرگاب',
				'mbarkh' => 'مبارکه',
				'mjlsy' => 'مجلسی',
				'dyzychh' => 'دیزیچه',
				'talkhvnchh' => 'طالخونچه',
				'krkvnd' => 'کرکوند',
				'zybashhr' => 'زیباشهر',
				'dh_srkh' => 'ده سرخ',
				'abvzydabad' => 'ابوزیدآباد',
				'aran_v_bydgl' => 'آران و بیدگل',
				'nvsh_abad' => 'نوش آباد',
				'sfyd_shhr' => 'سفید شهر',
				'asgran' => 'عسگران',
				'tyran' => 'تیران',
				'rzvanshhr_isfahan' => 'رضوانشهر',
				'chadgan' => 'چادگان',
				'rzvh' => 'رزوه',
				'dhaqan' => 'دهاقان',
				'glshn' => 'گلشن',
				'hbyb_abad' => 'حبیب آباد',
				'shapvrabad' => 'شاپورآباد',
				'kmshchh' => 'کمشچه',
				'khvrzvq' => 'خورزوق',
				'dstgrd' => 'دستگرد',
				'dvlt_abad' => 'دولت آباد',
				'syn' => 'سین',
				'khvr_isfahan' => 'خور',
				'frkhy' => 'فرخی',
				'jndq' => 'جندق',
				'bvyyn_v_myandsht' => 'بویین و میاندشت',
				'afvs' => 'افوس',
				'kvhpayh' => 'کوهپایه',
				'tvdshk' => 'تودشک',
				'sjzy' => 'سجزی',
				'nyk_abad' => 'نیک آباد',
				'mhmdabad' => 'محمدآباد',
				'nsrabad' => 'نصرآباد',
				'hsn_abad_isfahan' => 'حسن اباد',
				'vrznh' => 'ورزنه',
				'hrnd' => 'هرند',
				'azhyh' => 'اژیه',
			) ),
			'kerman' => array( 'label' => 'کرمان', 'cities' => array(
				'kerman' => 'کرمان',
				'sirjan' => 'سیرجان',
				'rafsanjan' => 'رفسنجان',
				'bam' => 'بم',
				'baft' => 'بافت',
				'bznjan' => 'بزنجان',
				'kshkvyyh' => 'کشکوییه',
				'brvat' => 'بروات',
				'dhbkry' => 'دهبکری',
				'drb_bhsht' => 'درب بهشت',
				'jbalbarz' => 'جبالبارز',
				'jyrft' => 'جیرفت',
				'aly_abad_kerman' => 'علی آباد',
				'blvk' => 'بلوک',
				'ms_srchshmh' => 'مس سرچشمه',
				'kshkvyyh_kerman' => 'کشکوییه',
				'bhrman' => 'بهرمان',
				'jvadyh_alhyh' => 'جوادیه الهیه',
				'sfayyh' => 'صفاییه',
				'zrnd' => 'زرند',
				'khanvk' => 'خانوک',
				'ryhan' => 'ریحان',
				'yzdan_shhr' => 'یزدان شهر',
				'syryz' => 'سیریز',
				'njf_shhr' => 'نجف شهر',
				'paryz' => 'پاریز',
				'hmashhr_kerman' => 'هماشهر',
				'khvajv_shhr' => 'خواجو شهر',
				'zydabad' => 'زیدآباد',
				'blvrd' => 'بلورد',
				'shhdad' => 'شهداد',
				'andvhjrd' => 'اندوهجرد',
				'glbaf' => 'گلباف',
				'shhrbabk' => 'شهربابک',
				'khvrsnd' => 'خورسند',
				'khatvn_abad' => 'خاتون آباد',
				'jvzm' => 'جوزم',
				'dhj' => 'دهج',
				'jvpar' => 'جوپار',
				'mahan' => 'ماهان',
				'mhy_abad' => 'محی آباد',
				'baghyn' => 'باغین',
				'zngy_abad_kerman' => 'زنگی آباد',
				'akhtyarabad' => 'اختیارآباد',
				'rayn' => 'راین',
				'chtrvd' => 'چترود',
				'kazm_abad' => 'کاظم آباد',
				'khnvj' => 'کهنوج',
				'dh_khan' => 'ده کهان',
				'chah_mryd' => 'چاه مرید',
				'brdsyr' => 'بردسیر',
				'dshtkar' => 'دشتکار',
				'lalh_zar' => 'لاله زار',
				'glzar' => 'گلزار',
				'ngar' => 'نگار',
				'hjdk' => 'هجدک',
				'ravr' => 'راور',
				'anbrabad' => 'عنبرآباد',
				'dvsary' => 'دوساری',
				'mrdhk' => 'مردهک',
				'mnvjan' => 'منوجان',
				'nvdzh' => 'نودژ',
				'kyanshhr' => 'کیانشهر',
				'kvhbnan' => 'کوهبنان',
				'rvdbar_kerman' => 'رودبار',
				'chah_dadkhda' => 'چاه دادخدا',
				'rmshk' => 'رمشک',
				'qlah_gnj' => 'قلعه گنج',
				'rhmt_abad_kerman' => 'رحمت آباد',
				'abas_abad_srdar' => 'عباس آباد سردار',
				'mhmdabad_kerman' => 'محمدآباد',
				'rabr' => 'رابر',
				'hnza' => 'هنزا',
				'fhrj' => 'فهرج',
				'dhnv_aslam_abad' => 'دهنو اسلام آباد',
				'anar' => 'انار',
				'amyn_shhr' => 'امین شهر',
				'nrmashyr' => 'نرماشیر',
				'nzam_shhr' => 'نظام شهر',
				'faryab' => 'فاریاب',
				'pasfyd' => 'پاسفید',
				'arzvyyh' => 'ارزوییه',
				'aly_abad_10800023001012' => 'علی آباد',
				'gnbky' => 'گنبکی',
				'zhklvt' => 'زهکلوت',
			) ),
			'kermanshah' => array( 'label' => 'کرمانشاه', 'cities' => array(
				'kermanshah' => 'کرمانشاه',
				'javanrud' => 'جوانرود',
				'eslamabad_e_gharb' => 'اسلامآباد غرب',
				'paveh' => 'پاوه',
				'hmyl' => 'حمیل',
				'hlshy' => 'هلشی',
				'rbat' => 'رباط',
				'kvzran' => 'کوزران',
				'qlah' => 'قلعه',
				'bayngan' => 'باینگان',
				'banvrh' => 'بانوره',
				'nvdshh' => 'نودشه',
				'nvsvd' => 'نوسود',
				'srpl_zhab' => 'سرپل ذهاب',
				'snqr' => 'سنقر',
				'str' => 'سطر',
				'svmar' => 'سومار',
				'qsrshyryn' => 'قصرشیرین',
				'kngavr' => 'کنگاور',
				'gvdyn' => 'گودین',
				'srmst' => 'سرمست',
				'gylanghrb' => 'گیلانغرب',
				'shrvynh' => 'شروینه',
				'dynvr' => 'دینور',
				'shnh' => 'صحنه',
				'bystvn' => 'بیستون',
				'hrsyn' => 'هرسین',
				'tazh_abad' => 'تازه آباد',
				'azglh' => 'ازگله',
				'myrabad_kermanshah' => 'میرآباد',
				'ghvarh' => 'گهواره',
				'krnd_kermanshah' => 'کرند',
				'ryjab' => 'ریجاب',
				'shahv' => 'شاهو',
				'rvansr' => 'روانسر',
			) ),
			'khuzestan' => array( 'label' => 'خوزستان', 'cities' => array(
				'ahvaz' => 'اهواز',
				'abadan' => 'آبادان',
				'dezful' => 'دزفول',
				'khorramshahr' => 'خرمشهر',
				'arvndknar' => 'اروندکنار',
				'chvybdh' => 'چویبده',
				'hsynyh' => 'حسینیه',
				'bydrvbh' => 'بیدروبه',
				'andymshk' => 'اندیمشک',
				'azady' => 'آزادی',
				'chm_glk' => 'چم گلک',
				'ahvaz1' => 'اهواز1',
				'ahvaz2' => 'اهواز2',
				'ahvaz3' => 'اهواز3',
				'ahvaz4' => 'اهواز4',
				'ahvaz5' => 'اهواز5',
				'ahvaz6' => 'اهواز6',
				'ahvaz7' => 'اهواز7',
				'ahvaz8' => 'اهواز8',
				'alhayy' => 'الهایی',
				'ayzh' => 'ایذه',
				'bndramam_khmyny' => 'بندرامام خمینی',
				'bndrmahshhr' => 'بندرماهشهر',
				'chmran' => 'چمران',
				'srdsht_khuzestan' => 'سردشت',
				'bhbhan' => 'بهبهان',
				'mnsvryh' => 'منصوریه',
				'tshan' => 'تشان',
				'mqavmt' => 'مقاومت',
				'mynvshhr' => 'مینوشهر',
				'hmzh' => 'حمزه',
				'salnd' => 'سالند',
				'shms_abad' => 'شمس آباد',
				'shhr_amam' => 'شهر امام',
				'sfy_abad' => 'صفی آباد',
				'myanrvd' => 'میانرود',
				'syah_mnsvr' => 'سیاه منصور',
				'mntzran' => 'منتظران',
				'chghamysh' => 'چغامیش',
				'jndy_shapvr' => 'جندی شاپور',
				'shhyvn' => 'شهیون',
				'bstan' => 'بستان',
				'svsngrd' => 'سوسنگرد',
				'kvt_sydnaym' => 'کوت سیدنعیم',
				'abvhmyzh' => 'ابوحمیظه',
				'ramhrmz' => 'رامهرمز',
				'rvd_zrd_mashyn' => 'رود زرد ماشین',
				'sltan_abad' => 'سلطان آباد',
				'bavj' => 'باوج',
				'shadgan' => 'شادگان',
				'khnafrh' => 'خنافره',
				'darkhvyn' => 'دارخوین',
				'shvshtr' => 'شوشتر',
				'shraft' => 'شرافت',
				'srdaran' => 'سرداران',
				'gvryh' => 'گوریه',
				'arb_hsn' => 'عرب حسن',
				'msjdslyman' => 'مسجدسلیمان',
				'glgyr' => 'گلگیر',
				'anbr' => 'عنبر',
				'shvsh' => 'شوش',
				'hr' => 'حر',
				'fth_almbyn' => 'فتح المبین',
				'hndyjan' => 'هندیجان',
				'bagh_mlk' => 'باغ ملک',
				'mydavd' => 'میداود',
				'qlah_tl' => 'قلعه تل',
				'jayzan' => 'جایزان',
				'amydyh' => 'امیدیه',
				'myankvh' => 'میانکوه',
				'laly' => 'لالی',
				'traz' => 'تراز',
				'zhrh' => 'زهره',
				'ramshyr' => 'رامشیر',
				'mshragh' => 'مشراگه',
				'trkalky' => 'ترکالکی',
				'smalh' => 'سماله',
				'gtvnd' => 'گتوند',
				'salh_shhr' => 'صالح شهر',
				'jnt_mkan' => 'جنت مکان',
				'abzhdan' => 'آبژدان',
				'zavvt' => 'زاووت',
				'qlah_khvajh' => 'قلعه خواجه',
				'hftgl' => 'هفتگل',
				'rfya' => 'رفیع',
				'hvyzh' => 'هویزه',
				'mlasany' => 'ملاثانی',
				'vys' => 'ویس',
				'shyban' => 'شیبان',
				'hmydyh' => 'حمیدیه',
				'aghajary' => 'آغاجاری',
				'jvlky' => 'جولکی',
				'kvt_abdalh' => 'کوت عبداله',
				'alvan' => 'الوان',
				'shavvr' => 'شاوور',
				'dhdz' => 'دهدز',
				'sydvn' => 'صیدون',
			) ),
			'kohgiluyeh_and_boyer_ahmad' => array( 'label' => 'کهگیلویه و بویراحمد', 'cities' => array(
				'yasuj' => 'یاسوج',
				'dugombadan' => 'دوگنبدان',
				'dehdasht' => 'دهدشت',
				'charam' => 'چرام',
				'madvan' => 'مادوان',
				'grab_sfly' => 'گراب سفلی',
				'chytab' => 'چیتاب',
				'spydar' => 'سپیدار',
				'qlah_ryysy' => 'قلعه رییسی',
				'dyshmvk' => 'دیشموک',
				'svq' => 'سوق',
				'patavh' => 'پاتاوه',
				'sy_skht' => 'سی سخت',
				'srasyab_yvsfy' => 'سرآسیاب یوسفی',
				'lykk' => 'لیکک',
				'qlah_mmby' => 'قلعه ممبی',
				'srfaryab' => 'سرفاریاب',
				'basht' => 'باشت',
				'bvstan' => 'بوستان',
				'lndh' => 'لنده',
				'margvn' => 'مارگون',
			) ),
			'kurdistan' => array( 'label' => 'کردستان', 'cities' => array(
				'sanandaj' => 'سنندج',
				'marivan' => 'مریوان',
				'saghez' => 'سقز',
				'baneh' => 'بانه',
				'armrdh' => 'آرمرده',
				'babarshany' => 'بابارشانی',
				'pyrtaj' => 'پیرتاج',
				'kany_svr' => 'کانی سور',
				'bvyyn_sfly' => 'بویین سفلی',
				'yasvknd' => 'یاسوکند',
				'byjar' => 'بیجار',
				'tvp_aghaj' => 'توپ آغاج',
				'sahb' => 'صاحب',
				'snth' => 'سنته',
				'shvyshh' => 'شویشه',
				'hsyn_abad' => 'حسین آباد',
				'qrvh' => 'قروه',
				'srysh_abad' => 'سریش آباد',
				'dzj' => 'دزج',
				'malvjh' => 'مالوجه',
				'dlbran' => 'دلبران',
				'brdh_rshh' => 'برده رشه',
				'chnarh' => 'چناره',
				'kany_dynar' => 'کانی دینار',
				'zrynh' => 'زرینه',
				'dyvandrh' => 'دیواندره',
				'hzarkanyan' => 'هزارکانیان',
				'kamyaran' => 'کامیاران',
				'mvchsh' => 'موچش',
				'avraman_tkht' => 'اورامان تخت',
				'srvabad' => 'سروآباد',
				'dhglan' => 'دهگلان',
				'blban_abad' => 'بلبان آباد',
			) ),
			'lorestan' => array( 'label' => 'لرستان', 'cities' => array(
				'khorramabad' => 'خرمآباد',
				'borujerd' => 'بروجرد',
				'dorud' => 'دورود',
				'aligoodarz' => 'الیگودرز',
				'shvl_abad' => 'شول آباد',
				'tytkan_bznvyd' => 'تیتکان بزنوید',
				'shahpvrabad' => 'شاهپوراباد',
				'chmn_sltan' => 'چمن سلطان',
				'ashtrynan' => 'اشترینان',
				'vnayy' => 'ونایی',
				'brvjrd1' => 'بروجرد1',
				'brvjrd2' => 'بروجرد2',
				'spyddsht' => 'سپیددشت',
				'byran_shhr' => 'بیران شهر',
				'zaghh' => 'زاغه',
				'khrm_abad1' => 'خرم آباد1',
				'khrm_abad2' => 'خرم آباد2',
				'khrm_abad3' => 'خرم آباد3',
				'hft_chshmh' => 'هفت چشمه',
				'nvrabad_lorestan' => 'نورآباد',
				'brkhvrdar' => 'برخوردار',
				'chalanchvlan' => 'چالانچولان',
				'drb_gnbd' => 'درب گنبد',
				'grab' => 'گراب',
				'kvhdsht' => 'کوهدشت',
				'kvhnany' => 'کوهنانی',
				'mvmn_abad' => 'مومن آباد',
				'azna' => 'ازنا',
				'pldkhtr' => 'پلدختر',
				'srab_hmam' => 'سراب حمام',
				'fyrvzabad_lorestan' => 'فیروزآباد',
				'alshtr' => 'الشتر',
				'srab_dvrh' => 'سراب دوره',
				'chm_plk' => 'چم پلک',
				'vysyan' => 'ویسیان',
				'svry' => 'سوری',
				'chqabl' => 'چقابل',
				'mamvlan' => 'معمولان',
			) ),
			'mazandaran' => array( 'label' => 'مازندران', 'cities' => array(
				'sari' => 'ساری',
				'babol' => 'بابل',
				'amol' => 'آمل',
				'qaem_shahr' => 'قائمشهر',
				'rynh' => 'رینه',
				'gznk' => 'گزنک',
				'dabvdsht' => 'دابودشت',
				'amamzadh_abdallh' => 'امامزاده عبدالله',
				'babkan' => 'بابکان',
				'khvsh_rvdpy' => 'خوش رودپی',
				'amyrkla' => 'امیرکلا',
				'glvgah' => 'گلوگاه',
				'mrzykla' => 'مرزیکلا',
				'zrgr' => 'زرگر',
				'gtab' => 'گتاب',
				'bhshhr' => 'بهشهر',
				'rstmkla' => 'رستمکلا',
				'khlyl_shhr' => 'خلیل شهر',
				'shyrvd' => 'شیرود',
				'tnkabn' => 'تنکابن',
				'nshtarvd' => 'نشتارود',
				'khrm_abad' => 'خرم آباد',
				'ramsr' => 'رامسر',
				'ktalm_v_sadat_shhr' => 'کتالم و سادات شهر',
				'dalkhany' => 'دالخانی',
				'kyasr' => 'کیاسر',
				'frym' => 'فریم',
				'payyn_hvlar' => 'پایین هولار',
				'aknd' => 'اکند',
				'bldh' => 'بلده',
				'frh_abad' => 'فرح آباد',
				'alasht' => 'آلاشت',
				'pl_sfyd' => 'پل سفید',
				'zyrab' => 'زیرآب',
				'qaym_shhr' => 'قایم شهر',
				'arth' => 'ارطه',
				'bhnmyr' => 'بهنمیر',
				'chmstan' => 'چمستان',
				'nvr' => 'نور',
				'rvyan' => 'رویان',
				'ayzdshhr' => 'ایزدشهر',
				'pvl' => 'پول',
				'kjvr' => 'کجور',
				'nvshhr' => 'نوشهر',
				'bablsr' => 'بابلسر',
				'hady_shhr' => 'هادی شهر',
				'srkhrvd' => 'سرخرود',
				'mhmvdabad_mazandaran' => 'محمودآباد',
				'nka' => 'نکا',
				'chalvs' => 'چالوس',
				'hchyrvd' => 'هچیرود',
				'mrzn_abad' => 'مرزن آباد',
				'kvhy_khyl' => 'کوهی خیل',
				'jvybar' => 'جویبار',
				'glvgah_mazandaran' => 'گلوگاه',
				'astanh_sra' => 'آستانه سرا',
				'frydvnknar' => 'فریدونکنار',
				'abas_abad' => 'عباس آباد',
				'slman_shhr' => 'سلمان شهر',
				'klarabad' => 'کلارآباد',
				'svrk' => 'سورک',
				'tbqdh' => 'طبقده',
				'kyakla' => 'کیاکلا',
				'shyrgah' => 'شیرگاه',
				'klardsht' => 'کلاردشت',
			) ),
			'markazi' => array( 'label' => 'مرکزی', 'cities' => array(
				'arak' => 'اراک',
				'saveh' => 'ساوه',
				'khomein' => 'خمین',
				'mahalat' => 'محلات',
				'davdabad' => 'داودآباد',
				'sarvq' => 'ساروق',
				'qvrchy_bashy' => 'قورچی باشی',
				'karchan' => 'کارچان',
				'ashtyan' => 'آشتیان',
				'tfrsh' => 'تفرش',
				'shhbaz' => 'شهباز',
				'avh' => 'آوه',
				'ghrq_abad' => 'غرق آباد',
				'nvbran' => 'نوبران',
				'dlyjan' => 'دلیجان',
				'nraq' => 'نراق',
				'mhajran_markazi' => 'مهاجران',
				'tvrh' => 'توره',
				'astanh' => 'آستانه',
				'shaznd' => 'شازند',
				'hndvdr' => 'هندودر',
				'javrsyan' => 'جاورسیان',
				'nymvr' => 'نیمور',
				'razqan' => 'رازقان',
				'mamvnyh' => 'مامونیه',
				'khshkrvd' => 'خشکرود',
				'prndk' => 'پرندک',
				'zavyh' => 'زاویه',
				'kmyjan' => 'کمیجان',
				'mylajrd' => 'میلاجرد',
				'khndab' => 'خنداب',
				'frmhyn' => 'فرمهین',
				'khnjyn' => 'خنجین',
				'tlkhab' => 'تلخاب',
			) ),
			'north_khorasan' => array( 'label' => 'خراسان شمالی', 'cities' => array(
				'bojnurd' => 'بجنورد',
				'shirvan' => 'شیروان',
				'jajarm' => 'جاجرم',
				'esfarayen' => 'اسفراین',
				'bjnvrd1' => 'بجنورد1',
				'bjnvrd2' => 'بجنورد2',
				'chnaran_shhr' => 'چناران شهر',
				'hsargrmkhan' => 'حصارگرمخان',
				'snkhvast' => 'سنخواست',
				'shvqan' => 'شوقان',
				'lvjly' => 'لوجلی',
				'khanlq' => 'خانلق',
				'zyart' => 'زیارت',
				'qvshkhanh' => 'قوشخانه',
				'tytkanlv' => 'تیتکانلو',
				'farvj' => 'فاروج',
				'qazy' => 'قاضی',
				'ava' => 'آوا',
				'ashkhanh' => 'آشخانه',
				'ayvr' => 'ایور',
				'grmh' => 'گرمه',
				'drq' => 'درق',
				'raz' => 'راز',
				'ghlaman' => 'غلامان',
				'ykh_savd' => 'یکه سعود',
				'sfy_abad_north_khorasan' => 'صفی آباد',
				'pysh_qlah' => 'پیش قلعه',
			) ),
			'razavi_khorasan' => array( 'label' => 'خراسان رضوی', 'cities' => array(
				'mashhad' => 'مشهد',
				'neyshabur' => 'نیشابور',
				'sabzevar' => 'سبزوار',
				'torbat_e_heydariyeh' => 'تربت حیدریه',
				'taybad' => 'تایباد',
				'karyz' => 'کاریز',
				'mshhd_ryzh' => 'مشهد ریزه',
				'bayk' => 'بایک',
				'kdkn' => 'کدکن',
				'nsrabad_razavi_khorasan' => 'نصرآباد',
				'nsr' => 'نسر',
				'rbat_sng' => 'رباط سنگ',
				'trbt_jam' => 'تربت جام',
				'ahmdabad_svlt' => 'احمدآباد صولت',
				'nyl_shhr' => 'نیل شهر',
				'smya_abad' => 'سمیع آباد',
				'chapshlv' => 'چاپشلو',
				'ltf_abad' => 'لطف آباد',
				'drgz' => 'درگز',
				'nvkhndan' => 'نوخندان',
				'bajgyran' => 'باجگیران',
				'rvdab' => 'روداب',
				'sbzvar1' => 'سبزوار1',
				'sbzvar2' => 'سبزوار2',
				'mzrj' => 'مزرج',
				'qvchan' => 'قوچان',
				'almajq' => 'آلماجق',
				'shhr_khnh' => 'شهر کهنه',
				'kashmr' => 'کاشمر',
				'frg_qlah' => 'فرگ قلعه',
				'bydkht' => 'بیدخت',
				'gnabad' => 'گناباد',
				'rvshnavnd' => 'روشناوند',
				'kakhk' => 'کاخک',
				'mlk_abad' => 'ملک آباد',
				'mshhd_10' => 'مشهد 10',
				'mshhd_12' => 'مشهد 12',
				'mshhd_11' => 'مشهد 11',
				'mshhd_samn' => 'مشهد ثامن',
				'rzvyh' => 'رضویه',
				'chknh' => 'چکنه',
				'bar' => 'بار',
				'fryman' => 'فریمان',
				'frhadgrd' => 'فرهادگرد',
				'chnaran' => 'چناران',
				'radkan' => 'رادکان',
				'sydabad' => 'سیدآباد',
				'sngan' => 'سنگان',
				'khvaf' => 'خواف',
				'nshtyfan' => 'نشتیفان',
				'qasm_abad' => 'قاسم آباد',
				'sdh_razavi_khorasan' => 'سده',
				'slamy' => 'سلامی',
				'mzdavnd' => 'مزدآوند',
				'srkhs' => 'سرخس',
				'qlndr_abad' => 'قلندر آباد',
				'sfyd_sng' => 'سفید سنگ',
				'anabd' => 'انابد',
				'brdskn' => 'بردسکن',
				'shhrabad' => 'شهرآباد',
				'jngl' => 'جنگل',
				'rshtkhvar' => 'رشتخوار',
				'chnar' => 'چنار',
				'shhr_zv' => 'شهر زو',
				'klat' => 'کلات',
				'hsn_abad_razavi_khorasan' => 'حسن آباد',
				'kndr' => 'کندر',
				'khlyl_abad' => 'خلیل آباد',
				'shadmhr' => 'شادمهر',
				'fyz_abad' => 'فیض آباد',
				'bjstan' => 'بجستان',
				'yvnsy' => 'یونسی',
				'trqbh' => 'طرقبه',
				'fyrvzh' => 'فیروزه',
				'shandyz' => 'شاندیز',
				'grmab' => 'گرماب',
				'hmt_abad' => 'همت آباد',
				'jghtay' => 'جغتای',
				'ryvadh' => 'ریواده',
				'dvlt_abad_razavi_khorasan' => 'دولت آباد',
				'chkhmaq' => 'چخماق',
				'mshkan_razavi_khorasan' => 'مشکان',
				'nqab' => 'نقاب',
				'hkm_abad' => 'حکم آباد',
				'bakhrz' => 'باخرز',
				'qlah_nv_alya' => 'قلعه نو علیا',
				'sltan_abad_razavi_khorasan' => 'سلطان آباد',
				'nvdh_anqlab' => 'نوده انقلاب',
				'davrzn' => 'داورزن',
				'ryvnd' => 'ریوند',
				'salh_abad_razavi_khorasan' => 'صالح آباد',
				'jnt_abad' => 'جنت آباد',
				'ryvsh' => 'ریوش',
				'drvd' => 'درود',
				'qdmgah' => 'قدمگاه',
				'khrv' => 'خرو',
				'glbhar' => 'گلبهار',
				'ashq_abad' => 'اسحق آباد',
				'shshtmd' => 'ششتمد',
				'shamkan' => 'شامکان',
				'glmkan' => 'گلمکان',
				'ashq_abad_razavi_khorasan' => 'عشق آباد',
			) ),
			'south_khorasan' => array( 'label' => 'خراسان جنوبی', 'cities' => array(
				'birjand' => 'بیرجند',
				'qayen' => 'قائن',
				'tabas' => 'طبس',
				'nehbandan' => 'نهبندان',
				'byrjnd1' => 'بیرجند1',
				'byrjnd2' => 'بیرجند2',
				'qhstan' => 'قهستان',
				'tbs_msyna' => 'طبس مسینا',
				'gzyk' => 'گزیک',
				'asdyh' => 'اسدیه',
				'srbyshh' => 'سربیشه',
				'mvd' => 'مود',
				'drh' => 'درح',
				'qayn' => 'قاین',
				'asfdn' => 'اسفدن',
				'khzry_dsht_byaz' => 'خضری دشت بیاض',
				'nymblvk' => 'نیمبلوک',
				'aryn_shhr' => 'آرین شهر',
				'shvsf' => 'شوسف',
				'srayan' => 'سرایان',
				'aysk' => 'آیسک',
				'sh_qlah' => 'سه قلعه',
				'baghstan' => 'باغستان',
				'aslamyh' => 'اسلامیه',
				'frdvs' => 'فردوس',
				'zhan' => 'زهان',
				'bshrvyh' => 'بشرویه',
				'arsk' => 'ارسک',
				'hajy_abad_south_khorasan' => 'حاجی آباد',
				'abyz' => 'آبیز',
				'khvsf' => 'خوسف',
				'mazhan' => 'ماژان',
				'ashq_abad_south_khorasan' => 'عشق آباد',
				'dyhvk' => 'دیهوک',
			) ),
			'qazvin' => array( 'label' => 'قزوین', 'cities' => array(
				'qazvin' => 'قزوین',
				'takestan' => 'تاکستان',
				'abeyek' => 'آبیک',
				'alvand' => 'الوند',
				'dansfhan' => 'دانسفهان',
				'shal' => 'شال',
				'bvyyn_zhra' => 'بویین زهرا',
				'sgzabad' => 'سگزآباد',
				'asmt_abad' => 'عصمت آباد',
				'ardaq' => 'ارداق',
				'asfrvryn' => 'اسفرورین',
				'khrmdsht' => 'خرمدشت',
				'zyaabad' => 'ضیاآباد',
				'nrjh' => 'نرجه',
				'malm_klayh' => 'معلم کلایه',
				'razmyan' => 'رازمیان',
				'syrdan' => 'سیردان',
				'aqbalyh' => 'اقبالیه',
				'mhmvdabadnmvnh' => 'محمودآبادنمونه',
				'kvhyn' => 'کوهین',
				'khakaly' => 'خاکعلی',
				'zyaran' => 'زیاران',
				'qshlaq' => 'قشلاق',
				'shryfyh' => 'شریفیه',
				'mhmdyh' => 'محمدیه',
				'bydstan' => 'بیدستان',
				'avj' => 'آوج',
				'abgrm' => 'آبگرم',
			) ),
			'qom' => array( 'label' => 'قم', 'cities' => array(
				'qom' => 'قم',
				'jafarieh' => 'جعفریه',
				'dastjerd' => 'دستجرد',
				'kahak' => 'کهک',
				'qnvat' => 'قنوات',
				'slfchgan' => 'سلفچگان',
				'qahan' => 'قاهان',
			) ),
			'semnan' => array( 'label' => 'سمنان', 'cities' => array(
				'semnan' => 'سمنان',
				'shahroud' => 'شاهرود',
				'damghan' => 'دامغان',
				'garmsar' => 'گرمسار',
				'amyryh' => 'امیریه',
				'dybaj' => 'دیباج',
				'klath' => 'کلاته',
				'bstam' => 'بسطام',
				'mjn' => 'مجن',
				'klath_khyj' => 'کلاته خیج',
				'byarjmnd' => 'بیارجمند',
				'rvdyan' => 'رودیان',
				'ayvanky' => 'ایوانکی',
				'khn_abad' => 'کهن آباد',
				'shhmyrzad' => 'شهمیرزاد',
				'mhdy_shhr' => 'مهدی شهر',
				'drjzyn' => 'درجزین',
				'aradan' => 'آرادان',
				'myamy' => 'میامی',
				'rzvan' => 'رضوان',
				'srkhh' => 'سرخه',
			) ),
			'sistan_and_baluchestan' => array( 'label' => 'سیستان و بلوچستان', 'cities' => array(
				'zahedan' => 'زاهدان',
				'chabahar' => 'چابهار',
				'zabol' => 'زابل',
				'iranshahr' => 'ایرانشهر',
				'bzman' => 'بزمان',
				'chah_bhar' => 'چاه بهار',
				'plan' => 'پلان',
				'khash' => 'خاش',
				'asmaayl_abad' => 'اسماعیل آباد',
				'dh_ryys' => 'ده رییس',
				'bnjar' => 'بنجار',
				'nsrt_abad' => 'نصرت آباد',
				'srjngl' => 'سرجنگل',
				'sravan' => 'سراوان',
				'mhmdy' => 'محمدی',
				'gsht' => 'گشت',
				'syrkan' => 'سیرکان',
				'asfndk' => 'اسفندک',
				'bnt' => 'بنت',
				'nyk_shhr' => 'نیک شهر',
				'chanf' => 'چانف',
				'pyshyn' => 'پیشین',
				'rask' => 'راسک',
				'parvd' => 'پارود',
				'knark' => 'کنارک',
				'jzynk' => 'جزینک',
				'zhk' => 'زهک',
				'dvst_mhmd' => 'دوست محمد',
				'qrqry' => 'قرقری',
				'glmvrty' => 'گلمورتی',
				'chgrd' => 'چگرد',
				'mhrstan' => 'مهرستان',
				'ashar' => 'آشار',
				'syb' => 'سیب',
				'svran' => 'سوران',
				'hydvch' => 'هیدوچ',
				'adymy' => 'ادیمی',
				'mhmdabad_sistan_and_baluchestan' => 'محمدآباد',
				'aly_akbr' => 'علی اکبر',
				'myrjavh' => 'میرجاوه',
				'ladyz' => 'لادیز',
				'ryg_mlk' => 'ریگ ملک',
				'qsrqnd' => 'قصرقند',
				'sarbvk' => 'ساربوک',
				'fnvj' => 'فنوج',
				'gtyj' => 'گتیج',
				'mhmdan' => 'محمدان',
				'bmpvr' => 'بمپور',
				'qasm_abad_sistan_and_baluchestan' => 'قاسم آباد',
				'nvk_abad' => 'نوک آباد',
				'brys' => 'بریس',
				'ngvr' => 'نگور',
				'srbaz' => 'سرباز',
				'jalq' => 'جالق',
				'aspkh' => 'اسپکه',
				'zrabad_sistan_and_baluchestan' => 'زرآباد',
			) ),
			'tehran' => array( 'label' => 'تهران', 'cities' => array(
				'tehran' => 'تهران',
				'rey' => 'ری',
				'shemiranat' => 'شمیرانات',
				'damavand' => 'دماوند',
				'thran_10' => 'تهران 10',
				'thran_11' => 'تهران 11',
				'thran_12' => 'تهران 12',
				'thran_13' => 'تهران 13',
				'thran_14' => 'تهران 14',
				'thran_15' => 'تهران 15',
				'thran_16' => 'تهران 16',
				'thran_17' => 'تهران 17',
				'thran_18' => 'تهران 18',
				'thran_19' => 'تهران 19',
				'thran_20' => 'تهران 20',
				'thran_21' => 'تهران 21',
				'thran_22' => 'تهران 22',
				'kylan' => 'کیلان',
				'absrd' => 'آبسرد',
				'rvdhn' => 'رودهن',
				'abaly' => 'آبعلی',
				'hsn_abad_tehran' => 'حسن آباد',
				'mlard' => 'ملارد',
				'sfadsht' => 'صفادشت',
				'pyshva' => 'پیشوا',
				'baqrshhr' => 'باقرشهر',
				'khryzk' => 'کهریزک',
				'qyam_dsht' => 'قیام دشت',
				'qlah_nv' => 'قلعه نو',
				'fshm' => 'فشم',
				'tjrysh' => 'تجریش',
				'shmshk' => 'شمشک',
				'lvasan' => 'لواسان',
				'jvadabad' => 'جوادآباد',
				'vramyn' => 'ورامین',
				'shhryar' => 'شهریار',
				'sbashhr' => 'صباشهر',
				'shahdshhr' => 'شاهدشهر',
				'baghstan_tehran' => 'باغستان',
				'andyshh' => 'اندیشه',
				'shhryar1' => 'شهریار1',
				'shhryar2' => 'شهریار2',
				'shhryar3' => 'شهریار3',
				'vhydyh' => 'وحیدیه',
				'frdvsyh' => 'فردوسیه',
				'chhardangh' => 'چهاردانگه',
				'aslam_shhr6' => 'اسلام شهر6',
				'aslamshhr' => 'اسلامشهر',
				'aslam_shhr1' => 'اسلام شهر1',
				'aslam_shhr2' => 'اسلام شهر2',
				'aslam_shhr3' => 'اسلام شهر3',
				'ahmd_abad_mstvfy' => 'احمد آباد مستوفی',
				'rbatkrym' => 'رباطکریم',
				'nsyrshhr' => 'نصیرشهر',
				'prnd' => 'پرند',
				'shryf_abad' => 'شریف آباد',
				'pakdsht' => 'پاکدشت',
				'frvn_abad' => 'فرون اباد',
				'arjmnd' => 'ارجمند',
				'fyrvzkvh' => 'فیروزکوه',
				'qds' => 'قدس',
				'jlyl_abad' => 'جلیل اباد',
				'glstan' => 'گلستان',
				'salhyh' => 'صالحیه',
				'nsym_shhr' => 'نسیم شهر',
				'bvmhn' => 'بومهن',
				'saydabad' => 'سعیداباد',
				'khsrvabad' => 'خسرواباد',
				'prdys' => 'پردیس',
				'qrchk' => 'قرچک',
			) ),
			'yazd' => array( 'label' => 'یزد', 'cities' => array(
				'yazd' => 'یزد',
				'meybod' => 'میبد',
				'ardakan' => 'اردکان',
				'taft' => 'تفت',
				'khranq' => 'خرانق',
				'ahmd_abad' => 'احمد آباد',
				'aqda' => 'عقدا',
				'bafq' => 'بافق',
				'nyr_yazd' => 'نیر',
				'bkh' => 'بخ',
				'mhryz' => 'مهریز',
				'yzd_mntqh_tarykhy' => 'یزد_منطقه تاریخی',
				'shahdyh' => 'شاهدیه',
				'hmydya' => 'حمیدیا',
				'ndvshn' => 'ندوشن',
				'bfrvyyh' => 'بفروییه',
				'khzrabad' => 'خضرآباد',
				'mhrdsht' => 'مهردشت',
				'abrkvh' => 'ابرکوه',
				'ashkzr' => 'اشکذر',
				'mjvmrd' => 'مجومرد',
				'hrat' => 'هرات',
				'bhabad' => 'بهاباد',
				'mrvst' => 'مروست',
				'zarch' => 'زارچ',
			) ),
			'zanjan' => array( 'label' => 'زنجان', 'cities' => array(
				'zanjan' => 'زنجان',
				'abhar' => 'ابهر',
				'khoramdareh' => 'خرمدره',
				'khodabandeh' => 'خدابنده',
				'sayyn_qlah' => 'صایین قلعه',
				'hydj' => 'هیدج',
				'grmab_zanjan' => 'گرماب',
				'zryn_rvd' => 'زرین رود',
				'qydar' => 'قیدار',
				'shrvrd' => 'سهرورد',
				'krsf' => 'کرسف',
				'nvrbhar' => 'نوربهار',
				'sjas' => 'سجاس',
				'nyk_py' => 'نیک پی',
				'armghankhanh' => 'ارمغانخانه',
				'hlb' => 'حلب',
				'zryn_abad' => 'زرین آباد',
				'chvrzq' => 'چورزق',
				'ab_br' => 'آب بر',
				'dndy' => 'دندی',
				'mah_nshan' => 'ماه نشان',
				'sltanyh' => 'سلطانیه',
			) ),
		);
	}

	public static function provinces() {
		$out = array();
		foreach ( self::iran_geography() as $key => $province ) { $out[ $key ] = $province['label']; }
		return $out;
	}

	public static function cities() {
		$out = array();
		foreach ( self::iran_geography() as $province_key => $province ) {
			foreach ( $province['cities'] as $city_key => $label ) { $out[ $city_key ] = $label; }
		}
		return $out;
	}

	public static function cities_for_province( $province_key ) {
		$province_key = sanitize_key( $province_key );
		$geography    = self::iran_geography();
		return isset( $geography[ $province_key ]['cities'] ) ? $geography[ $province_key ]['cities'] : array();
	}

	public static function city_province_map() {
		$out = array();
		foreach ( self::iran_geography() as $province_key => $province ) {
			foreach ( $province['cities'] as $city_key => $label ) { $out[ $city_key ] = $province_key; }
		}
		return $out;
	}

	public static function request_for() { return array( 'self' => 'برای خودم', 'other' => 'برای دیگری' ); }

	public static function service_types() {
		return array(
			'short_stay_tourist'   => 'درخواست ویزای کوتاه مدت/توریستی',
			'business'             => 'ویزای تجاری',
			'work'                 => 'ویزای کاری',
			'family_reunification' => 'ویزای خانوادگی / الحاق خانواده',
			'transit'              => 'ویزای ترانزیت',
			'long_stay'            => 'ویزای بلند مدت',
			'residence'            => 'اقامت',
		);
	}

	public static function family_relations() { return array( 'spouse' => 'همسر', 'child' => 'فرزند', 'father' => 'پدر', 'mother' => 'مادر', 'brother' => 'برادر', 'sister' => 'خواهر', 'grandfather' => 'پدربزرگ', 'grandmother' => 'مادربزرگ', 'grandchild' => 'نوه', 'other' => 'سایر' ); }

	public static function age_groups() { return array( 'infant' => 'نوزاد (۰ تا ۱ سال)', 'child' => 'کودک (۲ تا ۱۲ سال)', 'teenager' => 'نوجوان (۱۳ تا ۱۷ سال)', 'adult' => 'بزرگسال (۱۸ تا ۶۴ سال)', 'elderly' => 'سالمند (۶۵ سال به بالا)' ); }

	public static function age_group_boundaries() { return array( 'infant' => array( 'min' => 0, 'max' => 1 ), 'child' => array( 'min' => 2, 'max' => 12 ), 'teenager' => array( 'min' => 13, 'max' => 17 ), 'adult' => array( 'min' => 18, 'max' => 64 ), 'elderly' => array( 'min' => 65, 'max' => null ) ); }

	/**
	 * No city list is defined in FORMS.txt. These per-form lists intentionally
	 * start empty so projects can supply one without coupling the forms forever.
	 */
	public static function cities_for_form( $form_type ) {
		return self::for_form( 'cities', $form_type, self::cities() );
	}

	public static function occupations() {
		static $occupations = null;
		if ( null !== $occupations ) {
			return $occupations;
		}

		$data = <<<'DIDAR_OCCUPATIONS'
Business Owner|صاحب کسب و کار
Entrepreneur|کارآفرین
Company Director|مدیر شرکت
General Manager|مدیرعامل / مدیر کل
Operations Manager|مدیر عملیات
Project Manager|مدیر پروژه
Sales Manager|مدیر فروش
Marketing Manager|مدیر بازاریابی
Office Manager|مدیر اداری
HR Manager|مدیر منابع انسانی
Business Consultant|مشاور کسب و کار
Management Consultant|مشاور مدیریت
Executive|مدیر اجرایی
Supervisor|سرپرست
Team Leader|سرپرست تیم
Accountant|حسابدار
Auditor|حسابرس
Financial Analyst|تحلیلگر مالی
Financial Manager|مدیر مالی
Banker|بانکدار
Bank Manager|مدیر بانک
Investment Analyst|تحلیلگر سرمایه‌گذاری
Insurance Agent|کارگزار بیمه
Tax Consultant|مشاور مالیاتی
Economist|اقتصاددان
Software Engineer|مهندس نرم‌افزار
Software Developer|توسعه دهنده نرم‌افزار
Web Developer|توسعه دهنده وب
Web Designer|طراح وب
Computer Engineer|مهندس کامپیوتر
IT Specialist|متخصص فناوری اطلاعات
IT Manager|مدیر فناوری اطلاعات
Systems Analyst|تحلیلگر سیستم
Data Analyst|تحلیلگر داده
Data Scientist|دانشمند داده
Database Administrator|مدیر پایگاه داده
Network Engineer|مهندس شبکه
Network Administrator|مدیر شبکه
Cybersecurity Specialist|متخصص امنیت سایبری
Programmer|برنامه‌نویس
Mobile App Developer|توسعه دهنده اپلیکیشن موبایل
UX/UI Designer|طراح UX/UI
Artificial Intelligence Engineer|مهندس هوش مصنوعی
Civil Engineer|مهندس عمران
Mechanical Engineer|مهندس مکانیک
Electrical Engineer|مهندس برق
Electronics Engineer|مهندس الکترونیک
Chemical Engineer|مهندس شیمی
Industrial Engineer|مهندس صنایع
Architectural Engineer|مهندس معماری
Petroleum Engineer|مهندس نفت
Mining Engineer|مهندس معدن
Environmental Engineer|مهندس محیط زیست
Biomedical Engineer|مهندس پزشکی
Telecommunications Engineer|مهندس مخابرات
Structural Engineer|مهندس سازه
Automation Engineer|مهندس اتوماسیون
Doctor / Physician|پزشک
Surgeon|جراح
Dentist|دندانپزشک
Pharmacist|داروساز
Nurse|پرستار
Midwife|ماما
Physiotherapist|فیزیوتراپیست
Psychologist|روان شناس
Psychiatrist|روان پزشک
Medical Technician|تکنسین پزشکی
Laboratory Technician|تکنسین آزمایشگاه
Radiologist|رادیولوژیست
Veterinarian|دامپزشک
Medical Assistant|دستیار پزشکی
Paramedic|تکنسین فوریت‌های پزشکی
Nutritionist|متخصص تغذیه
Teacher|معلم
School Teacher|معلم مدرسه
University Professor|استاد دانشگاه
Lecturer|مدرس / استاد
Researcher|پژوهشگر
Scientist|دانشمند
University Student|دانشجوی دانشگاه
Student|دانش‌آموز / دانشجو
PhD Student|دانشجوی دکترا
Research Assistant|دستیار پژوهشی
Academic|عضو هیئت علمی / دانشگاهی
School Principal|مدیر مدرسه
Lawyer|وکیل
Attorney|وکیل دادگستری
Legal Consultant|مشاور حقوقی
Judge|قاضی
Prosecutor|دادستان
Notary|سردفتر / دفتر اسناد رسمی
Government Employee|کارمند دولت
Civil Servant|کارمند خدمات دولتی
Diplomat|دیپلمات
Public Official|مقام دولتی
Salesperson|فروشنده
Sales Representative|نماینده فروش
Retailer|خرده فروش
Shopkeeper|مغازه دار
Cashier|صندوقدار
Customer Service Representative|کارشناس خدمات مشتریان
Call Center Agent|اپراتور مرکز تماس
Real Estate Agent|مشاور املاک
Travel Agent|آژانس دار / کارگزار سفر
Tour Operator|برگزارکننده تور
Insurance Broker|کارگزار بیمه
Architect|معمار
Construction Manager|مدیر ساخت و ساز
Contractor|پیمانکار
Builder|سازنده
Electrician|برق کار
Plumber|لوله کش
Carpenter|نجار
Welder|جوشکار
Mason|بنا
Painter|نقاش ساختمان
Mechanic|مکانیک
Auto Mechanic|مکانیک خودرو
Technician|تکنسین
Machine Operator|اپراتور ماشین‌آلات
Construction Worker|کارگر ساختمانی
Driver|راننده
Taxi Driver|راننده تاکسی
Truck Driver|راننده کامیون
Bus Driver|راننده اتوبوس
Delivery Driver|راننده تحویل کالا
Pilot|خلبان
Flight Attendant|مهماندار هواپیما
Aircraft Engineer|مهندس هواپیما
Ship Captain|ناخدای کشتی
Seafarer|دریانورد
Sailor|ملوان
Logistics Manager|مدیر لجستیک
Warehouse Manager|مدیر انبار
Hotel Manager|مدیر هتل
Receptionist|پذیرشگر
Hotel Staff|کارمند هتل
Chef|سرآشپز
Cook|آشپز
Waiter|پیشخدمت
Bartender|متصدی بار
Baker|نانوا
Pastry Chef|شیرینی پز
Restaurant Manager|مدیر رستوران
Tour Guide|راهنمای گردشگری
Travel Consultant|مشاور سفر
Journalist|روزنامه نگار
Reporter|خبرنگار
Photographer|عکاس
Videographer|فیلم بردار
Filmmaker|فیلم ساز
Director|کارگردان
Producer|تهیه کننده
Actor|بازیگر
Musician|موسیقیدان
Singer|خواننده
Artist|هنرمند
Graphic Designer|طراح گرافیک
Illustrator|تصویرگر
Writer|نویسنده
Translator|مترجم
Interpreter|مترجم شفاهی
Farmer|کشاورز
Agricultural Engineer|مهندس کشاورزی
Farm Worker|کارگر مزرعه
Gardener|باغبان
Horticulturist|متخصص باغبانی
Fisherman|ماهیگیر
Forester|جنگلبان / متخصص جنگل
Agricultural Consultant|مشاور کشاورزی
Administrative Assistant|دستیار اداری
Secretary|منشی
Office Clerk|کارمند اداری
Receptionist|مسئول پذیرش
Executive Assistant|دستیار مدیر
Personal Assistant|دستیار شخصی
Human Resources Specialist|متخصص منابع انسانی
Procurement Officer|مسئول خرید
Purchasing Manager|مدیر خرید
Document Controller|مسئول کنترل اسناد
Architect|معمار (تکرار شده)
Interior Designer|طراح داخلی
Fashion Designer|طراح مد
Hairdresser|آرایشگر
Beautician|متخصص زیبایی
Fitness Trainer|مربی تناسب اندام
Sports Coach|مربی ورزشی
Athlete|ورزشکار
Security Guard|نگهبان
Police Officer|افسر پلیس
Firefighter|آتش نشان
Military Officer|افسر نظامی
Soldier|سرباز
Social Worker|مددکار اجتماعی
Librarian|کتابدار
Journalist|روزنامه نگار (تکرار شده)
Consultant|مشاور
Freelancer|فریلنسر / آزادکار
Religious Worker|فعال / کارمند مذهبی
Volunteer|داوطلب
DIDAR_OCCUPATIONS;

		$occupations = array();
		foreach ( preg_split( '/\R/u', trim( $data ) ) as $index => $line ) {
			$parts = explode( '|', $line, 2 );
			if ( 2 !== count( $parts ) ) {
				continue;
			}
			$key                 = sprintf( 'occupation_%03d', $index + 1 );
			$occupations[ $key ] = trim( $parts[1] );
		}

		// Keep the source catalog stable while making the fallback choice explicit.
		$occupations['other'] = 'سایر';
		$other = $occupations['other'];
		unset( $occupations['other'] );
		if ( class_exists( 'Collator' ) ) {
			$collator = new Collator( 'fa_IR' );
			uasort( $occupations, function ( $left, $right ) use ( $collator ) { return $collator->compare( $left, $right ); } );
		} else {
			uasort( $occupations, function ( $left, $right ) { return strcmp( $left, $right ); } );
		}
		$occupations['other'] = $other;

		return $occupations;
	}

	public static function occupations_for_form( $form_type ) {
		return self::for_form( 'occupations', $form_type, self::occupations() );
	}

	public static function academic_levels() {
		return array(
			'under_diploma' => 'زیردیپلم (Under Diploma)',
			'diploma'       => 'دیپلم (Diploma)',
			'associate'     => 'فوق‌دیپلم (Associate Degree)',
			'bachelor'      => 'کارشناسی (Bachelor’s Degree)',
			'master'        => 'کارشناسی ارشد (Master’s Degree)',
			'phd'           => 'دکترا (PHD)',
			'postdoc'       => 'فوق‌دکترا (Post-Doc)',
		);
	}

	public static function academic_levels_for_form( $form_type ) {
		return self::for_form( 'academic_levels', $form_type, self::academic_levels() );
	}

	public static function yes_no() {
		return array( 'yes' => 'بله', 'no' => 'خیر' );
	}

	public static function statuses() {
		return array(
			'pending_review'     => 'در انتظار بررسی',
			'initial_approval'   => 'تایید اولیه',
			'needs_correction'   => 'نیاز به اصلاح مدارک',
			'completed'          => 'تکمیل شده',
		);
	}

	/**
	 * Each form receives its own copy-on-write entry. Values are identical now,
	 * while a future form-specific change can replace only one map entry or use
	 * its dedicated filter without affecting the other forms.
	 */
	private static function for_form( $dataset, $form_type, $shared_options ) {
		$form_type = sanitize_key( $form_type );
		$lists     = array(
			'consultation'        => $shared_options,
			'embassy_appointment' => $shared_options,
			'traveler_evaluation' => $shared_options,
			'complaint_suggestion' => $shared_options,
			'visa_request'        => $shared_options,
		);

		$options = isset( $lists[ $form_type ] ) ? $lists[ $form_type ] : $shared_options;
		return apply_filters( 'didar_' . sanitize_key( $dataset ) . '_for_' . $form_type, $options, $form_type );
	}
}
